
[package]
description = "Platform aliases."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "plat"
repository = "https://github.com/vladasz/plat"
version = "0.8.0"


[dependencies]
cfg_aliases = "0.2"
